# 5-3. NumPyライブラリ

**NumPy**を使った多次元配列の操作について説明していきます。<br>
**NumPy**は多次元配列を効率的に扱うライブラリです。<br>
Pythonの標準ライブラリではありませんが、科学技術計算や機械学習など、ベクトルや行列の演算が多用される分野では、事実上の標準ライブラリとしての地位を確立しています。<br>
<br>
NumPyを用いるには、まず、**`numpy`** モジュールをインポートする必要があります。<br>
**`慣習として、`np` と別名をつけて利用されます。`**<br>

**`NumPyでは、Python標準の数値やリストの代わりに、`**<br>
**`特別な数値や配列を用いることで、格段に効率的な配列演算を実現します。`**

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

## 配列の構築

**配列**とは、特定の型の値の並びです。<br>
NumPyの 配列は**`numpy.array()`** 関数で作成します。<br>
配列の要素はPython標準のリストやタプルで指定します。<br>
どちらを用いて作成しても全く同じ配列を作成できます。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

py_a = [1, 2, 3]
a = np.array(py_a) # リストから配列作成
print(a)
py_b = (1, 2, 3)
b = np.array(py_b) # タプルからの配列作成
print(b)
print('NumPy array is python list: ', a is py_a)   # python のリストと、numpy の配列は別のもの
print('NumPy array is python tuple', b is py_b) # python のタプルと、numpy の配列は別のもの
print('NumPy array; from list is NumPy array; from tuple', a==b) # numpy 配列の要素を比較すると同値

`print` の結果はリストと似ていますが、要素が `,` ではなく空白で区切られているに注意してください。<br>
`print` ではなく、式の評価結果の場合、より違いが明示されます。<br>
<br>
配列は **`numpy.ndarray`** というデータ型によって実現されています。<br>
組み込み関数 `type()` を使うと、データ型を調べられます。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

py_a = [1, 2, 3]
a = np.array(py_a) # リストから配列作成

print(py_a)
print(a)

print(type(np.array([1,2,3,4,5]))) # 配列の型
print(type([1,2,3,4,5]))

実数には、小数点が付与されて印字されます。<br>
numpy.arrayの第２引数に、キーワード引数dtypeで、各要素の型を指定しています。<br>

In [ ]:
print(np.array([-1,0,1], dtype=np.int32))    # np.int32の代わりに'int32'でも同じ
print(np.array([-1,0,1], dtype=np.float64)) # np.float64の代わりに'float64'でも同じ

複素数は実部と虚部を表す実数の組であり、虚部には `j` が付与されて印字されます。

In [ ]:
print(np.array([-1,0,1], dtype=np.complex128)) # np.complex128の代わりに'complex128'でも同じ

数値から真理値への変換では、`0` が `False` で、`0` 以外が `True` になります。

In [ ]:
print(np.array([-1,0,1], dtype=np.bool_)) # np.bool_の代わりに'bool'でも同じ

### 多次元配列

**多次元配列**は、配列の中に配列がある入れ子の配列です。
入れ子のリストやタプルを `numpy.array()` に渡すことで構築できます。

In [ ]:
print(np.array([
  [1, 2],
  [3, 4]
])) # 2次元配列の構築

In [ ]:
print(np.array([
  [ [1, 2],
    [3, 4] ],
  [ [5, 6],
    [7, 8] ]
])) # 3次元配列の構築

上の例からわかるように、2次元配列は行列のように、3次元配列は行列の配列のように印字されます。

多次元配列は、要素となる配列の長さが等しいことが想定されます。
つまり、2次元配列は、行列のように各行の長さが等しくなければなりません。

In [11]:
print(np.array([[1,2],[3]])) # 行の長さが異なる場合

[list([1, 2]) list([3])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


行の長さが異なる場合は、多次元配列とは見做されません。<br>

多次元配列の各次元の長さの組を、多次元配列の**形** (shape) と呼びます。<br>
特に2次元配列の場合、行列と同様に、行数（内側にある配列の数）と列数（内側にある配列の要素数）の組を使って、行数×列数で形を表記します。<br>

1次元配列に対して **`reshape()`** メソッドを使うと、引数で指定された形の多次元配列に変換することができます。<br>

`reshape()` を適用する前後の配列（ここでは `a1` と `a2`）は、内部的にデータを共有していることに注意してください。<br>
つまり、`a1` の要素を更新すると、`a2` にも影響を及ぼします。

In [ ]:
a1 = np.array([3, 4, 5, 6, 7, 8]) # 1次元配列
a2 = a1.reshape(2,3)              # 2×3の2次元配列

a1[2] = 6
print(a1)
print(a2)

**`ravel()`** メソッドを使うと、多次元配列を1次元配列に戻すことができます。
`ravel()` の結果も、`reshape()` と同様に、元の配列と要素を共有します。

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5]).reshape(2,3) # ２次元配列に変換
print(a)                                                    # NumPyの２次元配列
print(a.ravel())                                          # もとの list に戻す

elems = np.array([0, 1, 2, 3, 4, 5])
a = elems.reshape(2,3).ravel()                   # ravel()は要素をelemsと共有
elems[1] = 6                                            # 配列のインデックス番号１に６を代入

print(elems)                                             # 作成した２次元配列を list に変換したもの
print(a)                                                    # list に変換したもの

なお、要素をコピーして変換する **`flatten()`** メソッドもありますが、コピーしない `ravel()` の方が効率的です。

### **配列のデータ属性**

配列はオブジェクトで、属性情報を所有しています。<br>
配列が持つ代表的なデータ属性（メソッド以外の属性）を次の表にまとめます。

| 属性 | 意味 |
|--- |---|
| `a.dtype` | 配列 `a` の要素型 |
| `a.shape` | 配列 `a` の形（各次元の長さのタプル）|
| `a.ndim` | 配列 `a` の次元数（`len(a.shape)` と等しい）|
| `a.size` | 配列 `a` の要素数（`a.shape` の総乗と等しい）|
| `a.flat` | 配列 `a` の1次元表現（`a.ravel()` と等しい）|
| `a.T` | 配列 `a` を転置した配列（`a` と要素を共有）|

## 配列要素を生成する構築関数

要素を指定して配列を作成する代表的な関数を紹介します。<br>
特に断りが無い場合、ここで紹介する関数は、`array()` と同様に `dtype` 引数で要素型を指定可能です。<br>

### `arange`

**`numpy.arange()`** は組み込み関数 `range()` の配列版です（`arange` は array range の略）。<br>
開始値・終了値・刻み幅を引数にとります。<br>
デフォルトの開始値は `0`、刻み幅は `1` です。
`range()` と違って、引数の値は整数に限定されません。


In [20]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

print(np.arange(3))               # range(3)に対応する配列
print(np.arange( 0,  1,  0.2 )) # 0を開始値として0.2刻みで1未満の要素を生成

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


### `linspace`
**`numpy.linspace()`** 関数は、範囲を等分割した値からなる配列を作成します。<br>
第1引数と第2引数には、開始値と終了値、第3引数には分割数を指定します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

print(np.linspace(0, 1, 4)) # 0から1の値を4分割した値を要素に持つ配列
print(np.linspace(0, 1, 5)) # 0から1の値を5分割した値を要素に持つ配列

### `zeros` と `ones`

**`numpy.zeros()`** 関数は、`0` を要素とする配列を作成します。<br>
同様に、**`numpy.ones()`** 関数は、`1` を要素とする配列を作成します。<br>
どちらも、作成される形を第1引数に取ります。<br>
デフォルトの要素型は、実数です。<br>

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

print(np.zeros( 4 ))       # 長さ4の1次元配列
print(np.zeros(( 2, 3 ))) # 2×3の2次元配列を生成
print(np.ones( 4 ))        # 長さ4の1次元配列
print(np.ones(( 2, 3 )))  # 2×3の2次元配列を生成

### `random.rand`

**`numpy.random.rand()`** 関数は、0 以上 1 未満の乱数からなる配列を生成します。<br>
引数には生成される配列の形を指定します。<br>
要素型は実数に限定されます。<br>

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

print(np.random.rand( 4 ))     # 長さ4の1次元配列
print(np.random.rand( 2, 3 )) # 2×3の2次元配列を生成

この他にも、**`numpy.random.randn()`**・**`numpy.random.binomial()`**・**`numpy.random.poisson()`** は、それぞれ、正規分布・二項分布・ポアソン分布の乱数からなる配列を生成します。

## 練習

引数に整数 $n$ を取り、$i$ から始まる連番の整数からなる配列を$i$番目 ($i\ge 0$) の行として持つ $n\times n$ の2次元配列を返す関数 `range_square_matrix()` を、`arange()` を用いて定義してください。

たとえば、`range_square_matrix(3)` は、
```
[[0 1 2]
 [1 2 3]
 [2 3 4]]
```
と印字されるような2次元配列を返します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

# 関数の定義
def arange_square_matrix(n):
    list = []                                        # 配列のリスト
    for i in range(n):
        list.append(np.arange(i, n + i))  # リストに配列を追加
    array = np.array(list)
    return array

# １行
def one_liner(n):
    return np.array([np.arange(i, n + i) for i in range(n)])

# 関数の検証
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))
print(all(map(all,(arange_square_matrix(4) == np.array([[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]])))))
print(all(map(all,(one_liner(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))
print(all(map(all,(one_liner(4) == np.array([[0,1,2,3],[1,2,3,4],[2,3,4,5],[3,4,5,6]])))))

## 配列要素の操作

### インデックスアクセス

配列の要素を、`0` から始まるインデックスを使って参照できます。<br>
配列の先頭要素のインデックスは `0`、最後の要素のインデックスは `-1` となります。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(3)
print('a:', a)
print('a[0]:', a[0])
print('a[-1]:', a[-1])

a[-1] = 3 # 要素への代入もできる
print('updated a:', a)

多次元配列では、高次元（入れ子の外側）から順にインデックスを指定します。
特に2次元配列、すなわち行列の場合は、行インデックスと列インデックスを順に指定します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(6).reshape(2,3)
print('a:\n', a)
print('a[1, 2]:', a[1, 2]) # 行と列のインデックスをまとめて指定
a[1,2] = 6                  # 要素に代入
print('updated a:\n', a)

### スライス

リストと同様に、配列も**スライス**することができます。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(5)
print(a)              # 全要素
print(a[ 1 : 4 ])   # インデックス 1 〜 3
print(a[ 1 : ])      # インデックス 1 〜 最後
print(a[ : -2 ])     # インデックス 0 〜 最後から２番目
print(a[ : : 2 ])    # インデックス 0 〜 最後 １おき
print(a[ : : -1 ])   # インデックス 0 〜 最後 最後から先頭

配列のスライスに対して代入すると、右辺の値がコピーされて、スライス元の配列にまとめて代入されます。

In [26]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

############
#
# np.array の場合
#

a = np.arange( 5 )
print(a)
a[ 1 : 4 ] = 6             # インデックス 1 〜 3
print(a)

a = np.arange( 5 )
a[ : : 2 ] = 6              # インデックス 0 〜 最後 １おき
print(a)

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]


一方、リストに対しては、以下はエラーになります。

In [ ]:
## NumPyのインポート
#import numpy as np # 慣習的な別名 'np'

############
#
# list の場合
#

a = [ 0, 1, 2, 3, 4 ]
print(a)
a[ 1 : 4 ] = [6] # インデックス 1 〜 3 を [6] で置き換える
print(a)

a[ 1 : 4 ] = 6 # インデックス １ 〜 3 に 6 を代入しようとすると、TypeError: can only assgin an iterable

多次元配列に対しては、インデックスの参照と同様に、高い次元のスライスから順に並べて指定します。<br>
多次元配列に対するスライスは、入れ子リストに対するスライスとは意味が異なることに注意してください。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange( 9 ).reshape( 3, 3 )
print( a )                # インデックス０（行）以上 × インデックス０（列）以上  ( 3 × 3 )
print( '' )
print( a[ : 2 , : 2 ] )  # インデックス １（行）まで × インデックス１（列）まで ( 2 × 2 )
print( '' )
print( a[ 1 : , 1 : ] )  # インデックス１（行）以上 × インデックス１（列）以上 ( 2 × 2 )
print( '' )
print( a[ 1 : , 0 : ] )  # インデックス１（行）以上 × インデックス０（列）以上 ( 2 × 3 )

### for文

リストと同様に、for文を用いて、配列要素への反復処理を記述できます。<br>

多次元配列の場合は、最外の配列に対して反復します。<br>
つまり、2次元配列の場合、行の配列に対する反復処理となります。<br>

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

for v in np.arange(3): # 1行の flat な配列
    print(v)

print('\n')

for row in np.arange(6).reshape(2,3):  # 2行×3列の2次元配列
    print(row)

for文と併用される `enumerate()` の多次元配列版として、`numpy.ndenumerate()` 関数が提供されています。<br>
`numpy.ndenumerate()` は、（多次元）インデックスと要素の組を列挙します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

nparange = np.arange(6).reshape(2, 3)
print(nparange)

print('\n')

for index, e in np.ndenumerate(nparange): # 2行3列を順番に数え上げる
    print(index, e)

print('\n')

nparange3 = np.arange(3)
for index, e in np.ndenumerate(nparange3):                    # 1行1列を順番に数え上げる
    print(index, e)

## 要素毎の演算

配列に対する要素毎の演算は、簡潔に記述できます。<br>
しかも、for文で記述するより、効率がよいです。<br>

### **配列のスカラー演算**

配列とスカラーとの算術演算を記述すると、要素毎のスカラー演算となります。<br>
演算結果として、新しい配列が返ります。<br>

### スカラー
スカラー（**`scalar`**  skay·luh「スケイラ」）は数値のことです。リストや配列でない。ただの数値のことをスカラーと呼びます。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(4)

print('a\t\t\t', a)

print('a + 1\t\t', a + 1)          # 各要素に1を加算
print('a - 1\t\t\t', a - 1)         # 各要素に1を減算
print('a * 2\t\t\t', a * 2)         # 各要素に2を乗算
print('a / 2\t\t\t', a / 2)        # 各要素を2で除算
print('a // 2\t\t', a // 2)        # 各要素を2で整数除算
print('a % 2\t\t', a % 2)        # 各要素に2の剰余演算
print('a ** 2\t\t', a ** 2)         # 各要素を2乗

print('1 + a\t\t', 1 + a)         # 左側がスカラでもよい
print('1 - a\t\t\t', 1 - a)        # 左側がスカラでもよい
print('2 * a\t\t\t', 2 * a)        # 左側がスカラでもよい

b = a + 1
print('1 / (a + 1)\t\t', 1 / b) # 左側がスカラでもよい
print('9 // (a + 1)\t', 9 // b) # 左側がスカラでもよい

### **配列同士の演算**

形が同じ配列同士の算術演算は、同じ位置の要素同士の演算となります。
演算結果として、新しい配列が返ります。

実は、形が同じでない配列同士の算術演算も可能ですが、振舞いが複雑なので間違いやすいです。<br>
配列同士の算術演算は、形が同じ配列に限定する方が賢明です。<br>

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
print(a)
print('')
print(b)
print('')
print(a + b) 
print('')
print(a - b)
print('')
print(a * b)
print('')
print(a / b)
print('')
c = 3 * a
print('')
print(c // b)
print('')
print(a % b)
print('')
print(a ** b)

### ユニバーサル関数
スカラー演算以外の演算<br>

NumPyには**ユニバーサル関数**と呼ばれる、任意の形の配列を取り、各要素に所定の演算を与えた結果を返す関数があります。<br>
その代表例は、**`numpy.sqrt()`** 関数です。<br>
この他にも、多数のユニバーサル関数が提供されています。<br>
詳しくは、[ユニバーサル関数の一覧](https://docs.scipy.org/doc/numpy-1.14.0/reference/ufuncs.html#available-ufuncs)を参照してください。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.zeros(3) + 2
print('a\t\t', a)
print('sqrt(a)\t', np.sqrt(a)) # 各要素はsqrt(2)

print('\nb')
b = np.zeros((2,2)) + 2
print(b)
print('\nnp.sqrt(b)')
print(np.sqrt(b)) # 各要素はsqrt(2)
print('\nnp.sqrt(2)')
print(np.sqrt(2)) # スカラ（0次元配列）も扱える

## よく使われる配列操作
### `dot`

**`numpy.dot()`** は、2つの配列を引数に取り、そのドット積を返します。<br>
両者が1次元配列のときは、ベクトル内積と等しいです。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

np.dot(np.arange( 0, 4 ), np.arange( 1, 5 )) # 0*1 + 1*2 + 2*3 + 3*4
np.dot(np.arange( 6 ), np.arange( 1, 8 )) # 0*1 + 1*2 + 2*3 + 3*4 + 4*5 + 5*6 + ?*7 長さが同じ配列でないと、ValueError

2次元配列同士のドット積だと、行列乗算と等しいです。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

# [[0 1]     [[1 2]
#  [2 3]] と  [3 4]] の行列積
print(np.dot(np.arange( 4 ).reshape( 2, 2 ), np.arange( 1, 5 ).reshape( 2, 2 )))

print('')

# [[0 1]]    [[1, 2, 3]]
#  [2 3]] と [4, 5, 6]] の行列積
print(np.dot(np.arange( 4 ).reshape( 2, 2 ), np.arange( 1, 7 ).reshape( 2, 3 )))

### `sort`

**`numpy.sort()`** 関数は、昇順でソートされた**新しい**配列を返します。<br>
これは、組み込み関数 `sorted()` の配列版です。<br>
一方、配列の **`sort()`** メソッドは、配列を破壊的に（インプレースで）ソートします。<br>
これは、リストの `sort()` メソッドの配列版です。

In [38]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.array([3, 4, -1, 0, 2])
print('a\t\t', a)

print('np.sort(a)\t', np.sort(a))  # numpy.sort()： 組み込み関数 sorted() の配列版

print('a\t\t', a)                        # a は変更されていない

a.sort()                                  # a を変更してしまう
print('a\t\t', a)                        # a.sort()： リストの sort() メソッドの配列版

a		 [ 3  4 -1  0  2]
np.sort(a)	 [-1  0  2  3  4]
a		 [ 3  4 -1  0  2]
a		 [-1  0  2  3  4]


### `sum`, `max`, `min`, `mean`

配列のメソッド **`sum()`**・**`max()`**・**`min()`**・**`mean()`** は、それぞれ総和・最大値・最小値・算術平均を返します。<br>
これらのメソッドは、引数が与えられない場合、全要素を集計した結果を返します。
多次元配列の場合、集計する次元を指定できます。<br>
具体的には、2次元配列の場合、`0` を指定すると各列に、`1` を指定すると各行に、対応するメソッドを適用した結果が返されます。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

# [[0 1 2]
#  [3 4 5]]
a = np.arange(6).reshape(2,3)
print(a)
print('')
print(a.sum())
print(a.sum(0))
print(a.sum(1))
print('')
print(a.mean(0))
print(a.mean(1))

この他にも、多数の数学・統計関連のメソッドや関数が提供されています。
詳しくは、[数学関数](https://docs.scipy.org/doc/numpy/reference/routines.math.html)や[統計関数](https://docs.scipy.org/doc/numpy/reference/routines.statistics.html)を参照してください。

## 配列の保存と復元

配列は、ファイルに保存したり、ファイルから読み出したりすることが、簡単にできます。

**`numpy.savetxt()`** 関数は、与えられた配列を指定されたファイル名をつけてテキスト形式で保存します。

In [ ]:
# google drive のマウント
from google.colab import drive
mnt = '/content/drive'
mydrive = mnt + '/MyDrive/'
drive.mount(mnt)
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

np.savetxt('/content/drive/MyDrive/arange3.txt', np.arange(3))
print(np.arange(3))

この `arange3.txt` は、次のような内容になっているはずです。
```
0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00


```
2次元配列は、列が空白区切りで保存されます

In [ ]:
# google drive のマウント
from google.colab import drive
mnt = '/content/drive'
mydrive = mnt + '/MyDrive/'
drive.mount(mnt)
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

np.savetxt(mydrive + '/arange2x3.txt', np.arange(6).reshape(2,3))

この `arange2x3.txt` は、次のような内容になっているはずです。
```
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00 5.000000000000000000e+00


```

一方、**`numpy.loadtxt()`** 関数は、与えられた名前のファイルに保存された配列を復元します。

In [ ]:
# google drive のマウント
from google.colab import drive
mnt = '/content/drive'
mydrive = mnt + '/MyDrive/'
drive.mount(mnt)
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.loadtxt(mydrive + '/arange2x3.txt')
print(a)

保存するときに、列の区切り文字を `delimiter` のキーワード引数で指定します。<br>区切り文字列はASCII（正確にはLatin-1）で解釈可能でなければなりません。<br>

また、保存するファイル名の拡張子を `.gz` とすると`savetxt()` は自動的にGZip形式で圧縮して保存します。<br>
読み込み時に、ファイル名の拡張子が`.gz` であれば、自動的に解凍して要見込みます。

## **真理値配列によるインデックスアクセス**

配列に対して、比較演算を適用すると、算術演算と同様に要素毎に演算されて、真理値の配列が返ります。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.arange(6)
print(a)
print(a < 3)

このように作られた真理値配列は、インデックスとして利用することができます。
これによって、条件を満たす範囲を取り出すような記述が可能になります。
次の具体例を見てみましょう。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

a = np.array([0,1,2,-3,-4,5,-6,-7])
print(a)
ind = a < 0
print('ind:', ind)
print(a[a < 0])                          # 負の要素を取り出し

ind = (a < 0) & (a % 2 == 0)
print('ind:', ind)
print(a[(a < 0) & (a % 2 == 0)]) # 負で偶数の要素を取り出し

ind = a < 0
print('ind:', ind)
a[a < 0] = 8                             # 負の要素を8に上書き
print(a)

一見すると単なる条件式のように見えますが、インデックスとなるのは真理値ではなく真理値の配列です。<br>
したがって、真理値を返す '`and`'、'`or`'、'`not`' の代わりに、要素毎の演算を行う '`&`'　、'`|`'、'`~`' を用いる必要があります。


## 線形代数の演算

`numpy.dot()` は、2次元配列を与えたときには、行列積となりました。
それだけでなく、行列積専用の **`numpy.matmul()`** も提供されています。

また、単位行列は **`numpy.identity()`** 関数で作成することができます。
引数に行列のサイズを指定します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

# [[1 0 0]
#  [0 1 0]
#  [0 0 1]] 3次の単位行列
I = np.identity(3)
print(I)

print('')

# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]
a = np.arange(9).reshape(3,3)
print(a)

print('')

# [[1 0 0]  [[0 1 2]   1x0 + 0x3 + 0x6    1x1 + 0x4 + 0x7    1x2 + 0x5 + 0x8    0 1 2
#  [0 1 0]   [3 4 5]   0x0 + 1x3 + 0x6    0x1 + 1x4 + 0x7    0x2 + 1x5 + 0x8    3 4 5
#  [0 0 1]]  [6 7 8]]  0x0 + 0x3 + 1x6    0x1 + 0x4 + 1x7    0x2 + 0x5 + 1x8    6 7 8
print(np.matmul(a, I))

**`numpy.linalg.norm()`** 関数は、与えられたベクトル（1次元配列）もしくは行列（2次元配列）のノルムを返します。

In [ ]:
# NumPyのインポート
import numpy as np # 慣習的な別名 'np'

print(np.ones(3))                        # 1**2 + 1**2 + 1**2
print(np.linalg.norm(np.ones(3))) # ユークリッドノルムを計算するのでsqrt(3)と等しい
print('')
identity = np.identity(3)
print(identity)
print(np.linalg.norm(identity))

NumPyでは、行列の分解、転置、行列式などの計算を含む線形代数の演算は、**`numpy.linalg`** モジュールで提供されています。
詳しくは、[線形代数関連関数](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)を参照してください。